### ISSUE TITLE
Issue with example data and error message within my own dataset

### ISSUE THREAD

**Issue by candour23** [mattlee821/EpiViz#3]
Hi, 

So I've tried running your example from github regarding 1 track.
" circos_plot(track_number = 1, # how many tracks do you want to plot
            track1_data = EpiViz::EpiViz_data1, # what is the dataframe for your first track
            track1_type = "points", # how do you want to plot your first track
            label_column = 1, # whats is the column of your labels
            section_column = 2, # what is the column of your sections
            estimate_column = 4, # what is the column of your estimate (beta, OR etc.)
            pvalue_column = 5, # what is the column of your p-value
            pvalue_adjustment = 1, # what do you want your p-value adjustment to be = 0.05/X
            lower_ci = 7, # what is the column of your lower confidence interval
            upper_ci = 8) # what is the column of your upper confidence interval"
            
I receive following error: Error in Summary.factor(c(5L, 4L, 6L, 7L, 8L, 9L, 79L, 80L, 3L, 12L, 11L,  : ‘min’ not meaningful for factors"
  
So the dataset example doesn't seem to be reproducible.
Furthermore, when tried my own dataset for circos plot, I receive a cryptic error: 
"Error in factor(data[[section_column]], labels = 1:nlevels(data[[section_column]])) : invalid 'labels'; length 2 should be 1 or 1"
  
I tried converting the labels to factors (like it is noted in your example), but didn't seem to fix it. Any suggestions?
Thanks for your time, I like the package and would really like to make it work.

**Comment by mattlee821** [comment]
Hey! 

1. issue with example in README - good spot, I've updated the README, this should work now!

2. This is an issue I haven't quite worked out how to fix properly yet. But a couple workarounds that will hopefully work:
a. the `section` column always needs to be a factor, but the `label` column could be a character or factor - try both
b. `data <- droplevels(data)` - use this function to remove any empty factor levels
c. create a new data frame with fake columns and then move your columns into that data frame. This is long winded but seems to fix the issue for most people. Example code using the `EpiViz_data1`:

```
# make some randomm labels
random_strings <- function(n = 5000) {
  a <- do.call(paste0, replicate(5, sample(LETTERS, n, TRUE), FALSE))
  paste0(a, sprintf("%04d", sample(9999, n, TRUE)), sample(LETTERS, n, TRUE))
}

# make your fake data frame with columns
data <- data.frame(
  beta = rnorm(nrow(EpiViz_data1), 0),
  pvalue = rnorm(nrow(EpiViz_data1), 0),
  lower_ci = rnorm(nrow(EpiViz_data1), 0),
  upper_ci = rnorm(nrow(EpiViz_data1), 0),
  label = random_strings(nrow(EpiViz_data1)),
  section = as.factor(rep(LETTERS[1:14], length.out = nrow(EpiViz_data1)))
  )

# move your real data into the fake data frame
data$b <- EpiViz_data1$beta
data$pvalue <- EpiViz_data1$pvalue
data$lower_ci <- EpiViz_data1$lower_confidence_interval
data$upper_ci <- EpiViz_data1$upper_confidence_interval
data$label <- EpiViz_data1$label
data$section <- EpiViz_data1$subclass

# plot
circos_plot(track_number = 1, 
            track1_data = data, 
            track1_type = "points", 
            label_column = 5, 
            section_column = 6, 
            estimate_column = 1, 
            pvalue_column = 2, 
            pvalue_adjustment = 1, 
            lower_ci = 3, 
            upper_ci = 4)
```

d. final option is to send me the data you are trying to plot and I can try to work out whats going.

**Comment by candour23** [comment]
Hey! It worked with the option c.! Thank you so much :)
