### ISSUE TITLE
How to solve: Error: Length of data and length of factors differ

### ISSUE THREAD

**Issue by ShengxinLiu** [mattlee821/EpiViz#4]
Hi,

Thanks for the great package! 

I have run into this 'Error: Length of data and length of factors differ', but am confused what does it mean. The dataframe I used was made almost exactly same as the example dataframe. Could you suggest how to solve it? 

Thanks in advance!

**Comment by mattlee821** [comment]
this is a factor issue - your dataframe thinks there are more/less factors than there is data. You can try a number of things:

1. drop any empty factor levels (sometimes works):
`droplevels()`


2. move your data into a new dataframe (sometimes works):
```
data_new <- data.frame(label = data$label, group = data$group, b = data$b,....)
```


3. make a new dataframe with simulated data and replaces it with your real data (almost always works):
```
# make some randomm labels
random_strings <- function(n = 5000) {
  a <- do.call(paste0, replicate(5, sample(LETTERS, n, TRUE), FALSE))
  paste0(a, sprintf("%04d", sample(9999, n, TRUE)), sample(LETTERS, n, TRUE))
}

# make your fake data frame with columns
data <- data.frame(
  beta = rnorm(nrow(EpiViz_data1), 0),
  pvalue = rnorm(nrow(EpiViz_data1), 0),
  lower_ci = rnorm(nrow(EpiViz_data1), 0),
  upper_ci = rnorm(nrow(EpiViz_data1), 0),
  label = random_strings(nrow(EpiViz_data1)),
  section = as.factor(rep(LETTERS[1:14], length.out = nrow(EpiViz_data1)))
  )

# move your data into these columns
data$beta <- my_data$b
data$pvalue <- my_data$pvalue
.....
```

**Comment by ShengxinLiu** [comment]
Thanks for the quick reply! The 2nd suggestion worked! Thx a lot!
